#!/usr/bin/env python3
"""
AI 日报生成脚本 - 中英文双语版
自动抓取 AI 新闻、技术文章、教程和趣闻，生成 HTML 页面
"""

import json
import os
from datetime import datetime

# 搜索结果文件路径
SEARCH_RESULTS_CN = "/Users/alex/.openclaw/workspace/ai-daily-news/search_results_cn.json"
SEARCH_RESULTS_EN = "/Users/alex/.openclaw/workspace/ai-daily-news/search_results_en.json"

def load_search_results(lang='cn'):
    """加载搜索结果"""
    file_path = SEARCH_RESULTS_CN if lang == 'cn' else SEARCH_RESULTS_EN
    if os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            return json.load(f)
    return {"news": [], "tech": [], "tutorial": [], "fun": []}

def generate_card(item, category_class, lang='cn'):
    """生成卡片 HTML"""
    title = item.get('title', '')
    snippet = item.get('snippet', '')
    if len(snippet) > 150:
        snippet = snippet[:150] + '...'
    url = item.get('url', '#')
    source = item.get('source', '') or extract_domain(url)
    
    return f'''
        <div class="card">
            <span class="card-category {category_class}">{get_category_label(category_class, lang)}</span>
            <h3><a href="{url}" target="_blank">{title}</a></h3>
            <p>{snippet}</p>
            <span class="card-source">{source}</span>
        </div>'''

def extract_domain(url):
    """提取域名"""
    try:
        from urllib.parse import urlparse
        return urlparse(url).netloc.replace('www.', '')
    except:
        return ''

def get_category_label(cat_class, lang='cn'):
    """获取分类标签"""
    labels_cn = {
        'category-news': '新闻',
        'category-tech': '技术',
        'category-tutorial': '教程',
        'category-fun': '趣闻'
    }
    labels_en = {
        'category-news': 'News',
        'category-tech': 'Tech',
        'category-tutorial': 'Tutorial',
        'category-fun': 'Fun'
    }
    labels = labels_cn if lang == 'cn' else labels_en
    return labels.get(cat_class, '')

def generate_html(news, tech, tutorial, fun, lang='cn'):
    """生成完整 HTML"""
    date = datetime.now()
    
    if lang == 'cn':
        date_str = date.strftime('%Y年%m月%d日 %A')
        title = "AI 日报"
        subtitle = "每日 AI 新闻资讯、技术文章、教程和趣闻"
        section_names = {
            'news': '📰 AI 新闻',
            'tech': '💻 技术文章',
            'tutorial': '📚 教程',
            'fun': '🎉 趣闻'
        }
        footer_text = "由 🐟 小鱼 自动生成"
    else:
        date_str = date.strftime('%B %d, %Y')
        title = "AI Daily News"
        subtitle = "Daily AI News, Tech Articles, Tutorials & Fun Stuff"
        section_names = {
            'news': '📰 AI News',
            'tech': '💻 Tech Articles',
            'tutorial': '📚 Tutorials',
            'fun': '🎉 Fun Stuff'
        }
        footer_text = "Generated by 🐟 Fish"
    
    news_cards = '\n'.join([generate_card(item, 'category-news', lang) for item in news])
    tech_cards = '\n'.join([generate_card(item, 'category-tech', lang) for item in tech])
    tutorial_cards = '\n'.join([generate_card(item, 'category-tutorial', lang) for item in tutorial])
    fun_cards = '\n'.join([generate_card(item, 'category-fun', lang) for item in fun])
    
    empty_msg_cn = '<p style="color:#64748b;">暂无内容</p>'
    empty_msg_en = '<p style="color:#64748b;">No content yet</p>'
    empty_msg = empty_msg_cn if lang == 'cn' else empty_msg_en
    
    html = f'''<!DOCTYPE html>
<html lang="{lang}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title} - {date.strftime('%Y-%m-%d')}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
            min-height: 100vh;
            padding: 20px;
        }}
        .container {{ max-width: 1200px; margin: 0 auto; }}
        header {{ text-align: center; padding: 40px 0; color: #fff; }}
        header h1 {{
            font-size: 2.5rem; margin-bottom: 10px;
            background: linear-gradient(90deg, #00d4ff, #7c3aed);
            -webkit-background-clip: text; -webkit-text-fill-color: transparent;
        }}
        header p {{ color: #94a3b8; font-size: 1.1rem; }}
        .lang-switch {{
            text-align: center; margin-bottom: 20px;
        }}
        .lang-switch a {{
            display: inline-block; padding: 8px 20px; margin: 0 10px;
            border-radius: 20px; text-decoration: none; font-weight: 600;
            transition: all 0.3s;
        }}
        .lang-switch a.active {{
            background: linear-gradient(90deg, #00d4ff, #7c3aed);
            color: #fff;
        }}
        .lang-switch a:not(.active) {{
            background: rgba(255,255,255,0.1);
            color: #94a3b8;
        }}
        .lang-switch a:hover {{ transform: scale(1.05); }}
        .date {{ text-align: center; color: #64748b; margin-bottom: 30px; font-size: 1.1rem; }}
        .section {{ margin-bottom: 40px; }}
        .section-title {{
            color: #fff; font-size: 1.5rem; margin-bottom: 20px;
            padding-left: 15px; border-left: 4px solid #00d4ff;
        }}
        .cards {{ display: grid; grid-template-columns: repeat(auto-fill, minmax(350px, 1fr)); gap: 20px; }}
        .card {{
            background: rgba(255, 255, 255, 0.05); border-radius: 16px; padding: 24px;
            border: 1px solid rgba(255, 255, 255, 0.1); transition: transform 0.3s, box-shadow 0.3s;
            backdrop-filter: blur(10px);
        }}
        .card:hover {{ transform: translateY(-5px); box-shadow: 0 20px 40px rgba(0, 0, 0, 0.3); }}
        .card-category {{
            display: inline-block; padding: 4px 12px; border-radius: 20px;
            font-size: 0.75rem; font-weight: 600; margin-bottom: 12px;
        }}
        .category-news {{ background: linear-gradient(90deg, #ff6b6b, #ee5a24); }}
        .category-tech {{ background: linear-gradient(90deg, #00d4ff, #0984e3); }}
        .category-tutorial {{ background: linear-gradient(90deg, #00b894, #00cec9); }}
        .category-fun {{ background: linear-gradient(90deg, #a29bfe, #6c5ce7); }}
        .card h3 {{ color: #fff; font-size: 1.2rem; margin-bottom: 12px; line-height: 1.4; }}
        .card h3 a {{ color: inherit; text-decoration: none; }}
        .card h3 a:hover {{ color: #00d4ff; }}
        .card p {{ color: #94a3b8; font-size: 0.9rem; line-height: 1.6; margin-bottom: 16px; }}
        .card-source {{ color: #64748b; font-size: 0.8rem; }}
        footer {{ text-align: center; padding: 40px 0; color: #64748b; font-size: 0.9rem; }}
        footer a {{ color: #00d4ff; text-decoration: none; }}
        @media (max-width: 768px) {{ .cards {{ grid-template-columns: 1fr; }} header h1 {{ font-size: 2rem; }} }}
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>🐟 {title}</h1>
            <p>{subtitle}</p>
        </header>
        
        <div class="lang-switch">
            <a href="index-cn.html" class="{'active' if lang == 'en' else ''}">中文</a>
            <a href="index.html" class="{'active' if lang == 'cn' else ''}">English</a>
        </div>
        
        <p class="date">{date_str}</p>
        
        <div class="section">
            <h2 class="section-title">{section_names['news']}</h2>
            <div class="cards">{news_cards if news_cards else empty_msg}</div>
        </div>
        
        <div class="section">
            <h2 class="section-title">{section_names['tech']}</h2>
            <div class="cards">{tech_cards if tech_cards else empty_msg}</div>
        </div>
        
        <div class="section">
            <h2 class="section-title">{section_names['tutorial']}</h2>
            <div class="cards">{tutorial_cards if tutorial_cards else empty_msg}</div>
        </div>
        
        <div class="section">
            <h2 class="section-title">{section_names['fun']}</h2>
            <div class="cards">{fun_cards if fun_cards else empty_msg}</div>
        </div>
        
        <footer>
            <p>{footer_text} | <a href="https://github.com/wallerwvw-cell/ai-daily-news">GitHub</a></p>
        </footer>
    </div>
</body>
</html>'''
    return html

def main():
    """主函数"""
    # 生成中文版
    results_cn = load_search_results('cn')
    html_cn = generate_html(
        results_cn.get('news', []),
        results_cn.get('tech', []),
        results_cn.get('tutorial', []),
        results_cn.get('fun', []),
        'cn'
    )
    with open("/Users/alex/.openclaw/workspace/ai-daily-news/index-cn.html", 'w', encoding='utf-8') as f:
        f.write(html_cn)
    print("✅ 中文版生成完成: index-cn.html")
    
    # 生成英文版
    results_en = load_search_results('en')
    html_en = generate_html(
        results_en.get('news', []),
        results_en.get('tech', []),
        results_en.get('tutorial', []),
        results_en.get('fun', []),
        'en'
    )
    with open("/Users/alex/.openclaw/workspace/ai-daily-news/index.html", 'w', encoding='utf-8') as f:
        f.write(html_en)
    print("✅ 英文版生成完成: index.html")

if __name__ == "__main__":
    main()
